FROM python:3.10.4-slim-bullseye

ENV BUILD_DEPS="\
gcc \
python3-dev \
libffi-dev \
cargo"

RUN apt-get update --assume-yes --quiet \
    && apt-get install \
        --assume-yes \
        --quiet \
        --no-install-recommends \
        $BUILD_DEPS\
    && pip install --no-cache-dir "pip==22.1.2" "poetry==1.2.0b3" \
    && poetry config virtualenvs.create false \
    && apt-get purge -y --auto-remove $BUILD_DEPS

CMD ["/bin/sh"]
