name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  lint-images:
    runs-on: ubuntu-latest
    container:
      image: hadolint/hadolint:v2.9.3-debian
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: hadolint *Dockerfile*

  rebuild-images:
    runs-on: ubuntu-latest
    needs: lint-images
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.py310-poetry12
          platforms: linux/amd64
          push: true
          tags: eugenetriguba/python:3.10-poetry1.2
          cache-from: type=gha
          cache-to: type=gha,mode=max
