name: ci

on: [push]

jobs:
  lint-images:
    runs-on: ubuntu-latest
    container:
      image: hadolint/hadolint:v2.12.0-debian
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: hadolint *Dockerfile*
  rebuild-image:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: lint-images
    strategy:
      matrix:
        include:
          - file: Dockerfile.py310-poetry12
            tag: eugenetriguba/python:3.10-poetry1.2
          - file: Dockerfile.py311-poetry12
            tag: eugenetriguba/python:3.11-poetry1.2
          - file: Dockerfile.py313-poetry18
            tag: eugenetriguba/python:3.13-poetry1.8
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.file }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ matrix.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
