name: Rebuild py310-poetry12

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
# This will only run on the default branch, which is 'main' and desirable in this case.
on:
  workflow_run:
    workflows: ["lint"]
    types:
      - completed

jobs:
  rebuild-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.py310-poetry12
          platforms: linux/amd64
          push: true
          tags: eugenetriguba/python:3.10-poetry1.2
          cache-from: type=gha
          cache-to: type=gha,mode=max
